

export const APP_TEXT = {
  appTitle: "Contractor Bill Master",
  contractorDetails: "Contractor / Business Details",
  clientDetails: "Client Details",
  profiles: "Saved Profiles",
  selectProfile: "Select a Profile",
  saveProfile: "Save as New Profile",
  deleteProfile: "Delete Profile",
  name: "Name",
  company: "Company / Brand Name",
  gstin: "GSTIN (GST Number)",
  phone: "Phone",
  email: "Email",
  website: "Website",
  social: "Social Media Links",
  addSocial: "Add Social Link",
  selectPlatform: "Select Platform",
  urlPlaceholder: "Paste profile URL here",
  accountDetails: "Bank Account Details",
  bankFields: {
    holderName: "Account Holder Name",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    upiId: "UPI ID",
    branchAddress: "Bank Address / Branch"
  },
  paymentQr: "Payment QR Code",
  uploadQr: "Upload QR",
  removeQr: "Remove QR",
  uploadLogo: "Upload Logo",
  removeLogo: "Remove Logo",
  address: "Site Address",
  date: "Date",
  billNumber: "Bill No.",
  billDate: "Bill Date",
  paymentStatus: "Payment Status",
  status: {
    Paid: "Paid",
    Pending: "Pending",
    Partial: "Partial"
  },
  addItem: "Add Item",
  updateItem: "Update Item",
  cancelEdit: "Cancel Edit",
  description: "Description / Work Item",
  length: "Length",
  width: "Width",
  height: "Height / Depth",
  quantity: "Qty",
  rate: "Rate",
  unit: "Unit",
  amount: "Amount",
  floor: "Floor / Level",
  floors: {
    GF: "Ground Floor",
    FF: "1st Floor",
    SF: "2nd Floor",
    TF: "3rd Floor",
    FF4: "4th Floor",
    FF5: "5th Floor",
    FF6: "6th Floor",
    FF7: "7th Floor",
    FF8: "8th Floor",
    FF9: "9th Floor",
    FF10: "10th Floor",
    Basement: "Basement",
    Terrace: "Terrace",
    External: "External/Site"
  },
  totalArea: "Total Qty/Area",
  totalAmount: "Total Amount",
  generateExcel: "Excel",
  generatePdf: "PDF",
  share: "Share Bill",
  shareText: "Here is the bill for the work.",
  shareModalTitle: "Share Bill",
  shareOptions: {
    text: "Text Summary",
    pdf: "PDF File",
    excel: "Excel File"
  },
  sharePreview: "Message Preview",
  copyToClipboard: "Copy to Clipboard",
  shareViaApp: "Share via App",
  calculator: "Calculator",
  cancel: "Cancel",
  confirm: "Add to Bill",
  sqft: "Sq.ft",
  rft: "R.ft",
  nos: "Nos/Pcs",
  cuft: "Cu.ft",
  clear: "Clear All",
  emptyList: "No items added yet. Use the form to add items.",
  billSummary: "Bill Summary",
  subTotal: "Sub Total",
  addGst: "Add GST",
  gstRate: "GST Rate (%)",
  gstAmount: "GST Amount",
  grandTotal: "Grand Total",
  advanceReceived: "Advance Received",
  balanceDue: "Balance Due",
  history: "History",
  saveBill: "Save Bill",
  savedBills: "Saved Bills",
  noSavedBills: "No saved bills found.",
  load: "Edit / Customize",
  delete: "Delete",
  billSaved: "Bill saved successfully!",
  profileSaved: "Profile saved successfully!",
  confirmDelete: "Are you sure?",
  loadDraft: "Draft Loaded",
  newBill: "New Bill",
  searchPlaceholder: "Search items...",
  disclaimer: "Terms & Conditions / Disclaimer",
  disclaimerPlaceholder: "e.g., Payment due within 7 days. Goods once sold will not be taken back.",
  platforms: {
    Instagram: "Instagram",
    Facebook: "Facebook",
    YouTube: "YouTube",
    Twitter: "Twitter (X)",
    LinkedIn: "LinkedIn",
    WhatsApp: "WhatsApp"
  },
  paymentHistory: "Payment History",
  addPayment: "Add Payment",
  paymentDate: "Date",
  paymentAmount: "Amount",
  paymentNote: "Purpose/Note (Optional)",
  totalAdvance: "Total Advance",
  remove: "Remove",
  trash: "Trash / Bin",
  restore: "Restore",
  permanentDelete: "Delete Forever",
  emptyTrash: "Trash is empty.",
  restoreSuccess: "Bill restored to history.",
  deleteSuccess: "Bill permanently deleted.",
  moveToTrash: "Move to Trash",
  voiceEntry: "Voice Entry",
  voiceEntryHint: "Tap mic & say: 'Pillar Concrete 10 by 10 by 5 rate 500'",
  voiceHints: {
    sqft: "Try: 'Wall Paint 10 by 12 rate 25'",
    rft: "Try: 'Pipe Work 100 feet rate 45'",
    nos: "Try: 'Panel 4 pieces rate 250'",
    cuft: "Try: 'Concrete 10 by 10 by 2 rate 300'",
    brass: "Try: 'Sand filling 10 by 10 by 5 rate 4000'",
    visit: "Try: 'Site Visit 5 times rate 2000'"
  },
  listening: "Listening...",
  processing: "Processing...",
  speechNotSupported: "Speech recognition is not supported in this browser. Please use Chrome or Edge.",
  browserNotSupported: "Browser not supported"
};

// Comprehensive list of units for all trades
export const CONSTRUCTION_UNITS = [
  // Area
  { value: "sq.ft", label: "Sq.ft (Area)" },
  { value: "sq.mt", label: "Sq.Mtr (Area)" },
  { value: "sq.yd", label: "Sq.Yard (Land)" },
  { value: "acre", label: "Acre (Land)" },
  
  // Linear
  { value: "rft", label: "R.ft (Linear)" },
  { value: "r.mt", label: "R.Mtr (Linear)" },
  
  // Volume / Civil
  { value: "cu.ft", label: "Cu.ft (Volume)" },
  { value: "cu.mt", label: "Cu.Mtr (Volume)" },
  { value: "brass", label: "Brass (100 Cu.ft)" },
  
  // Weight
  { value: "kg", label: "Kg (Weight)" },
  { value: "ton", label: "Ton (Weight)" },
  { value: "quintal", label: "Quintal (100Kg)" },
  
  // Count / Simple
  { value: "nos", label: "Nos/Pcs" },
  { value: "bag", label: "Bag" },
  { value: "box", label: "Box" },
  { value: "pkt", label: "Packet" },
  { value: "ltr", label: "Litre" },
  
  // MEP / Services
  { value: "point", label: "Point (Elec)" },
  { value: "kw", label: "kW (Load)" },
  { value: "hp", label: "HP (Motor)" },
  { value: "set", label: "Set" },
  
  // Time / Service
  { value: "hours", label: "Hours" },
  { value: "days", label: "Days" },
  { value: "month", label: "Month" },
  { value: "visit", label: "Visit" },
  
  // Other
  { value: "lsum", label: "Lump Sum" },
  { value: "%", label: "% Cost" }
];

// Database of standard construction items for Auto-Suggest
export const AUTO_SUGGEST_ITEMS = [
  // --- SITE PREP & CIVIL ---
  "Site Cleaning & Jungle Clearance",
  "Demolition of Old Structure",
  "Demolition of Brick Wall (4 inch)",
  "Demolition of Brick Wall (9 inch)",
  "Demolition of RCC Slab/Beam",
  "Debris Removal / Carting Away",
  "Excavation Work (Manual)",
  "Excavation Work (JCB / Mechanical)",
  "Backfilling with Earth/Soil",
  "Sand Filling (River Sand)",
  "PCC Work (1:4:8 Ratio)",
  "PCC Work (1:3:6 Ratio)",
  "Soling Work (Rubble Stone)",
  "Anti-Termite Treatment (Piping)",
  "Anti-Termite Treatment (Chemical)",
  
  // --- RCC & STRUCTURE ---
  "RCC Work M20 Grade",
  "RCC Work M25 Grade",
  "RCC Column Casting",
  "RCC Beam Casting",
  "RCC Slab Casting (5 inch)",
  "RCC Slab Casting (6 inch)",
  "Steel Reinforcement (Cutting & Bending)",
  "Shuttering Work (Ply & Batten)",
  "Shuttering Work (MS Plates)",
  "Lintel Beam Casting",
  "Loft Slab Casting",
  "Kitchen Platform Slab",
  
  // --- MASONRY ---
  "Brickwork 9 inch (Red Bricks)",
  "Brickwork 4.5 inch (Red Bricks)",
  "Block Work 4 inch (AAC Blocks)",
  "Block Work 6 inch (AAC Blocks)",
  "Block Work 8 inch (AAC Blocks)",
  "Fly Ash Brick Masonry",
  "Stone Masonry (Random Rubble)",
  "Parapet Wall Masonry",
  
  // --- PLASTER & FINISHING ---
  "Internal Plaster (12mm Neeru Finish)",
  "Internal Plaster (12mm Sand Faced)",
  "External Plaster (20mm Sand Faced)",
  "External Plaster (Double Coat)",
  "Ceiling Plastering",
  "Gypsum Plastering (Direct on Brick)",
  "Wall Putty Application (2 Coats)",
  "Waterproofing (Bathroom Sunk)",
  "Waterproofing (Terrace - Brickbat)",
  "Waterproofing (Chemical Coating)",
  
  // --- FLOORING & TILING ---
  "PCC Bed for Flooring",
  "Vitrified Tile Flooring (2x2)",
  "Vitrified Tile Flooring (4x2)",
  "Vitrified Tile Flooring (2x4)",
  "GVT/PGVT Tile Flooring",
  "Ceramic Floor Tiles (Anti-skid)",
  "Wall Tiles / Dado (Bathroom)",
  "Wall Tiles / Dado (Kitchen)",
  "Highlighter Wall Tiles",
  "Granite Flooring",
  "Italian Marble Flooring",
  "Indian Marble Flooring",
  "Kota Stone Flooring",
  "Wooden Flooring (Laminate)",
  "Vinyl Flooring / PVC",
  "Epoxy Grouting",
  "Skirting Fixing (3/4 inch)",
  "Granite Door Frame (Choukhat)",
  "Granite Window Sill",
  "Granite Staircase Tappa/Riser",
  "Marble Moulding / Edge Polishing",
  "Kitchen Countertop (Granite)",
  "Tile Cleaning & Acid Wash",
  
  // --- PAINTING & POLISHING ---
  "Wall Primer (Water Based)",
  "Wall Putty (Acrylic)",
  "Plastic Emulsion Paint (Tractor)",
  "Premium Emulsion Paint (Royal)",
  "Texture Paint (One Wall)",
  "External Apex Paint",
  "External Ultima Paint",
  "Distemper Paint",
  "Enamel Paint on Grills/Doors",
  "Oil Paint on Wall",
  "Melamine Polish (Matte/Glossy)",
  "PU Polish on Veneer",
  "Duco Paint Finish",
  "Lamination / Clear Coat",
  
  // --- POP & FALSE CEILING (Specialized) ---
  "POP False Ceiling (Plain Level)",
  "POP False Ceiling (Step/Cove)",
  "POP Punning on Walls (Smooth)",
  "Gypsum Board False Ceiling",
  "Gypsum Ceiling with Cove",
  "Grid Ceiling (2x2 Tiles)",
  "Metal Ceiling / Linear Ceiling",
  "Baffle Ceiling (Acoustic)",
  "PVC False Ceiling (Panel)",
  "POP Cornice (Running ft)",
  "POP Moulding / Beading",
  "POP Flower / Center Piece",
  "POP Patta / Band",
  "Cove Light Cutting & Framing",
  "Curtain Pelmet (POP)",
  "Trap Door Making (POP/Gypsum)",
  
  // --- CARPENTRY & JOINERY ---
  "Wooden Door Frame (Teak/Sal)",
  "Flush Door Shutter (30mm)",
  "Laminate Pasting on Door",
  "Veneer Pasting on Door",
  "Door Hardware Fixing (Handle/Lock)",
  "Window Frame (Wood)",
  "Wardrobe Making (Ply + Laminate)",
  "Wardrobe Internal (White Laminate)",
  "Kitchen Cabinet (Base Unit)",
  "Kitchen Cabinet (Wall Unit)",
  "Loft Shutters (Ply + Laminate)",
  "TV Unit Making",
  "Bed Making (Hydraulic)",
  "Study Table / Workstation",
  "Shoe Rack Making",
  "Plywood Paneling on Wall",
  "Wooden Partition (Double Side)",
  "Glass Partition with Wooden Frame",
  "Mosquito Net Door (Jali)",
  
  // --- FABRICATION (METAL) ---
  "MS Safety Grill (Square Bar)",
  "MS Safety Grill (Flat Bar)",
  "MS Main Gate (Sliding)",
  "MS Main Gate (Swing)",
  "SS Railing (304 Grade)",
  "SS Railing with Glass",
  "MS Staircase Fabrication",
  "Spiral Staircase (MS)",
  "MS Shed Fabrication (Roofing)",
  "Roofing Sheet Fixing (Color Coated)",
  "Polycarbonate Sheet Fixing",
  "Collapsible Gate Installation",
  "Rolling Shutter Installation",
  
  // --- ALUMINIUM & GLASS ---
  "Aluminium Sliding Window (2 Track)",
  "Aluminium Sliding Window (3 Track)",
  "Aluminium Section (Domal Series)",
  "Aluminium Section (Bombay Sliding)",
  "Aluminium Partition (12mm Board)",
  "Aluminium Partition (Glass)",
  "Aluminium Door (Bakelite Sheet)",
  "UPVC Window Installation",
  "Toughened Glass Partition (12mm)",
  "Glass Door with Patch Fittings",
  "Shower Cubicle (Glass)",
  "Mirror Fixing (Beveled/Plain)",
  "ACP Sheet Cladding (Exterior)",
  "ACP Signage Board",
  
  // --- PLUMBING & SANITARY ---
  "CPVC Pipe Laying (Internal)",
  "CPVC Pipe Laying (External)",
  "UPVC Pipe Laying",
  "SWR Pipe Laying (Drainage)",
  "PVC Rainwater Pipe (4 inch/6 inch)",
  "Core Cutting (Concrete Slab/Beam)",
  "Concealed Tank Installation",
  "Wall Hung WC Installation",
  "Indian Seat Installation",
  "Wash Basin Fixing (Counter)",
  "Wash Basin Fixing (Pedestal)",
  "Diverter Body Installation",
  "Mixer / Tap Fixing",
  "Shower Head Fixing",
  "Kitchen Sink Fixing",
  "Water Tank Installation (500L/1000L)",
  "Water Pump / Motor Installation",
  "Chamber Making (2x2)",
  "Manhole Cover Fixing",
  "Gas Pipeline Installation",
  
  // --- ELECTRICAL ---
  "Point Wiring (1.0 sqmm)",
  "Power Point Wiring (2.5 sqmm)",
  "AC Point Wiring (4.0 sqmm)",
  "Light Point (Ceiling/Wall)",
  "Fan Point",
  "Exhaust Fan Point",
  "Two-Way Switch Point",
  "TV / Telephone / Data Point",
  "Sub-Main Wiring (6 sqmm/10 sqmm)",
  "Conduit Pipe Laying (Slab)",
  "Conduit Pipe Laying (Wall Chasing)",
  "Metal Box Fixing",
  "Modular Switch Plate Fixing",
  "MCB Box / DB Installation",
  "MCB / ELCB Fixing",
  "Tube Light / Batten Fixing",
  "Ceiling Fan Installation",
  "Wall Fan Installation",
  "Chandelier Installation",
  "Profile Light Installation",
  "Strip Light / Rope Light Fixing",
  "Foot Light / Night Light",
  "Earthing Work (Plate/Pipe)",
  "Inverter & Battery Wiring",
  "CCTV Camera Installation",
  "Video Door Phone Installation",
  "Speaker Wire Laying",
  
  // --- HVAC & MISC ---
  "Split AC Installation",
  "Copper Piping for AC",
  "Drain Pipe for AC",
  "Cassette AC Installation",
  "AC Ducting Work",
  "Solar Panel Structure",
  "Solar Water Heater Installation",
  "Garden Grass Carpet",
  "Paver Block Fixing",
  "Kerb Stone Fixing",
  
  // --- CONSULTANT / PROFESSIONAL ---
  "Site Visit Charges",
  "Architectural Layout Design",
  "Structural Drawing Charges",
  "3D Elevation Design",
  "Interior Design Consultation",
  "Project Management Fees",
  "Supervisor Salary (Monthly)",
  "Daily Labor Charges (Helper)",
  "Daily Labor Charges (Mistri)",
  "Material Transport Charges",
  "Debris Carting (Tractor/Truck)"
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'monthly',
    name: 'Monthly Plan',
    price: 99,
    originalPrice: 99,
    durationMonths: 1,
    saveLabel: '',
    recommended: false
  },
  {
    id: '3-month',
    name: '3-Month Plan',
    price: 249,
    originalPrice: 297,
    durationMonths: 3,
    saveLabel: 'Save 15%',
    recommended: false
  },
  {
    id: '6-month',
    name: '6-Month Plan',
    price: 449,
    originalPrice: 594,
    durationMonths: 6,
    saveLabel: 'Save 25%',
    recommended: true
  },
  {
    id: 'yearly',
    name: 'Yearly Plan',
    price: 699,
    originalPrice: 1188,
    durationMonths: 12,
    saveLabel: 'Save 40%',
    recommended: false
  }
];

export const PAYMENT_METHODS = [
  { id: 'upi', name: 'UPI (GPay, PhonePe, Paytm)', icon: '📱' },
  { id: 'card', name: 'Debit / Credit Card', icon: '💳' },
  { id: 'netbanking', name: 'Net Banking', icon: '🏦' },
  { id: 'wallet', name: 'Wallets', icon: '👛' },
];
