
export const APP_TEXT = {
  appTitle: "Contractor Bill Master",
  contractorDetails: "My Business",
  clientDetails: "Client",
  profiles: "Saved Profiles",
  selectProfile: "Select a Profile",
  saveProfile: "Save Profile",
  deleteProfile: "Delete Profile",
  savedClients: "Saved Clients",
  saveClient: "Save Client",
  name: "Name",
  company: "Company / Brand Name",
  gstin: "GSTIN (GST Number)",
  phone: "Phone",
  email: "Email",
  website: "Website",
  social: "Social Media Links",
  addSocial: "Add Social Link",
  selectPlatform: "Select Platform",
  urlPlaceholder: "Paste profile URL here",
  accountDetails: "Bank Account Details",
  bankFields: {
    holderName: "Account Holder Name",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    upiId: "UPI ID",
    branchAddress: "Bank Address / Branch"
  },
  paymentQr: "Payment QR Code",
  uploadQr: "Upload QR",
  removeQr: "Remove QR",
  uploadLogo: "Upload Logo",
  removeLogo: "Remove Logo",
  address: "Site Address",
  date: "Date",
  billNumber: "Bill No.",
  estimateNumber: "Est. No.",
  billDate: "Bill Date",
  estimateDate: "Est. Date",
  paymentStatus: "Payment Status",
  estimateStatus: "Estimate Status",
  status: {
    Paid: "Paid",
    Pending: "Pending",
    Partial: "Partial"
  },
  estStatus: {
    Draft: "Draft",
    PendingApproval: "Pending Approval",
    InReview: "In Review",
    Approved: "Approved",
    Rejected: "Rejected"
  },
  addItem: "Add Item",
  updateItem: "Update Item",
  cancelEdit: "Cancel Edit",
  description: "Description / Item Name",
  length: "Length",
  width: "Width",
  height: "Height",
  quantity: "Qty",
  rate: "Rate",
  unit: "Unit",
  amount: "Amount",
  floor: "Floor",
  floors: {
    GF: "Ground Floor",
    FF: "1st Floor",
    SF: "2nd Floor",
    TF: "3rd Floor",
    FF4: "4th Floor",
    FF5: "5th Floor",
    FF6: "6th Floor",
    FF7: "7th Floor",
    FF8: "8th Floor",
    FF9: "9th Floor",
    FF10: "10th Floor",
    Basement: "Basement",
    Terrace: "Terrace",
    External: "External/Site"
  },
  totalArea: "Total Area",
  totalAmount: "Total Amount",
  generateExcel: "Excel",
  generatePdf: "PDF",
  share: "Share",
  shareText: "Here is your bill.",
  shareModalTitle: "Share Bill",
  shareOptions: {
    text: "WhatsApp / Text Summary",
    pdf: "PDF File",
    excel: "Excel File"
  },
  sharePreview: "Message Preview",
  copyToClipboard: "Copy",
  shareViaApp: "Share via App",
  calculator: "Calculator",
  cancel: "Cancel",
  confirm: "Add Item",
  sqft: "Sq.ft",
  rft: "R.ft",
  nos: "Nos/Pcs",
  cuft: "Cu.ft",
  clear: "Clear All",
  emptyList: "No items added yet. Tap 'Add Item' to start.",
  billSummary: "Bill Summary",
  subTotal: "Sub Total",
  addGst: "Add GST",
  gstRate: "GST Rate (%)",
  gstAmount: "GST Amount",
  grandTotal: "Grand Total",
  advanceReceived: "Advance Received",
  balanceDue: "Balance Due",
  history: "History",
  saveBill: "Save Bill",
  saveEstimate: "Save Estimate",
  savedBills: "Saved Bills",
  noSavedBills: "No saved items.",
  load: "Edit",
  convertToInvoice: "Convert to Invoice",
  delete: "Delete",
  billSaved: "Bill saved successfully!",
  estimateSaved: "Estimate saved successfully!",
  profileSaved: "Profile saved successfully!",
  clientSaved: "Client saved successfully!",
  confirmDelete: "Are you sure?",
  loadDraft: "Draft Loaded",
  newBill: "New Bill",
  newEstimate: "New Estimate",
  searchPlaceholder: "Search items...",
  disclaimer: "Terms & Conditions",
  disclaimerPlaceholder: "e.g., Payment due within 7 days.",
  platforms: {
    Instagram: "Instagram",
    Facebook: "Facebook",
    YouTube: "YouTube",
    Twitter: "Twitter (X)",
    LinkedIn: "LinkedIn",
    WhatsApp: "WhatsApp"
  },
  paymentHistory: "Payment History",
  addPayment: "Add Payment",
  paymentDate: "Date",
  paymentAmount: "Amount",
  paymentNote: "Note",
  totalAdvance: "Total Advance",
  remove: "Remove",
  trash: "Trash",
  restore: "Restore",
  permanentDelete: "Delete Forever",
  emptyTrash: "Trash is empty.",
  restoreSuccess: "Item restored.",
  deleteSuccess: "Deleted forever.",
  moveToTrash: "Move to Trash",
  voiceEntry: "Voice Entry",
  voiceEntryHint: "Tap mic & say: 'Pillar Concrete 10 by 10 by 5 rate 500'",
  voiceHints: {
    sqft: "Try: 'Wall Paint 10 by 12 rate 25'",
    rft: "Try: 'Pipe Work 100 feet rate 45'",
    nos: "Try: 'Panel 4 pieces rate 250'",
    cuft: "Try: 'Concrete 10 by 10 by 2 rate 300'",
    brass: "Try: 'Sand filling 10 by 10 by 5 rate 4000'",
    visit: "Try: 'Site Visit 5 times rate 2000'"
  },
  listening: "Listening...",
  processing: "Processing...",
  speechNotSupported: "Speech recognition is not supported in this browser. Please use Chrome or Edge.",
  browserNotSupported: "Browser not supported",
  modeInvoice: "Invoice / Bill",
  modeEstimate: "Estimate / Quote"
};

export const DASHBOARD_TEXT = {
  title: "Dashboard",
  totalRevenue: "Total Revenue",
  totalExpenses: "Total Expenses",
  netProfit: "Net Profit",
  profitMargin: "Margin",
  outstanding: "Due Amount",
  monthlyTrend: "Monthly Trend",
  topClients: "Top Clients",
  recentActivity: "Recent Activity",
  addExpense: "Add Expense",
  expenseHistory: "Expenses",
  noExpenses: "No expenses recorded.",
  profitOnBill: "Profit on Bill"
};

// Comprehensive list of units for all trades
export const CONSTRUCTION_UNITS = [
  // Area
  { value: "sq.ft", label: "Sq.ft" },
  { value: "sq.mt", label: "Sq.Mt" },
  { value: "sq.yd", label: "Sq.Yd" },
  { value: "acre", label: "Acre" },
  
  // Linear
  { value: "rft", label: "R.ft" },
  { value: "r.mt", label: "R.Mt" },
  
  // Volume / Civil
  { value: "cu.ft", label: "Cu.ft" },
  { value: "cu.mt", label: "Cu.Mt" },
  { value: "brass", label: "Brass" },
  
  // Weight
  { value: "kg", label: "Kg" },
  { value: "ton", label: "Ton" },
  { value: "quintal", label: "Quintal" },
  
  // Count / Simple
  { value: "nos", label: "Nos" },
  { value: "bag", label: "Bag" },
  { value: "box", label: "Box" },
  { value: "pkt", label: "Pkt" },
  { value: "ltr", label: "Ltr" },
  
  // MEP / Services
  { value: "point", label: "Point" },
  { value: "kw", label: "kW" },
  { value: "hp", label: "HP" },
  { value: "set", label: "Set" },
  
  // Time / Service
  { value: "hours", label: "Hours" },
  { value: "days", label: "Days" },
  { value: "month", label: "Month" },
  { value: "visit", label: "Visit" },
  
  // Other
  { value: "lsum", label: "Lump Sum" },
  { value: "%", label: "% Cost" }
];

export const EXPENSE_CATEGORIES = [
  "Material",
  "Labor",
  "Transport",
  "Food/Tea",
  "Equipment Rent",
  "Fuel",
  "Sub-contractor",
  "Other"
];

// Database of standard construction items for Auto-Suggest
export const AUTO_SUGGEST_ITEMS = [
  // ... (Keep existing massive list) ...
  // SITE PREP & CIVIL
  "Site boundary marking",
  "Site cleaning and debris removal",
  "Tree cutting (if required)",
  "Topsoil removal",
  "Temporary site fencing installation",
  "Temporary site office setup",
  "Excavation layout marking",
  "Excavation depth checking",
  "Excavation using JCB",
  "Manual excavation in tight areas",
  "Trench leveling",
  "Excavated soil stacking",
  "Soil compaction using manual rammer",
  "Soil compaction using plate compactor",
  "PCC bed marking",
  "PCC mixing",
  "PCC pouring",
  "PCC leveling",
  "PCC curing",
  "Foundation centerline marking",
  "Column starter marking",
  "Rebar cutting",
  "Rebar bending",
  "Rebar tying",
  "Footing reinforcement placement",
  "Spacer block installation under rebars",
  "Anti-termite chemical treatment",
  "Shuttering plank cleaning",
  "Shuttering oil application",
  "Footing shuttering setup",
  "Footing level checking",
  "Ready-mix concrete ordering",
  "Concrete slump test",
  "Concrete cube sample casting",
  "Footing concreting with vibrator",
  "Leveling footing concrete",
  "Footing curing",
  "Column starter shuttering",
  "Column reinforcement tying",
  "Column shuttering box installation",
  "Column plumb alignment",
  "Column concreting",
  "Column curing",
  "Foundation wall brickwork",
  "Foundation backfilling",
  "Backfill compaction",
  "Plinth beam shuttering",
  "Plinth beam reinforcement",
  "Plinth beam concreting",
  "Plinth beam curing",
  "Plinth filling with murrum",
  "Murrum compaction",
  "DPC (Damp Proof Course) application",
  "Layout for ground floor wall",
  "Brick/Block masonry line marking",
  "Brick soaking",
  "Mortar mixing",
  "Bricklaying",
  "Masonry level checking",
  "Masonry joint alignment",
  "Door frame marking",
  "Door frame installation",
  "Window frame marking",
  "Window frame installation",
  "Lintel shuttering",
  "Lintel reinforcement tying",
  "Lintel concreting",
  "Lintel curing",
  "Masonry up to slab height",
  "Slab shuttering plate installation",
  "Slab prop installation",
  "Slab scaffolding setup",
  "Shuttering leveling",
  "Shuttering gap sealing",
  "Beam bottom shuttering",
  "Beam side shuttering",
  "Beam reinforcement cutting",
  "Beam reinforcement placing",
  "Column rod extension tying",
  "Slab reinforcement mesh fabrication",
  "Reinforcement cover block placement",
  "Slab conduit layout marking",
  "Electrical conduit bending",
  "Electrical conduit fixing in slab",
  "Drain pipe sleeve installation",
  "AC copper pipe sleeve installation",
  "Plumbing sleeve installation",
  "Slab level checking",
  "Slab concrete pump setup",
  "Concrete pipeline balancing",
  "Slab concreting",
  "Needle vibrator operation",
  "Beam concreting",
  "Leveling slab using straightedge",
  "Slab finishing",
  "Slab curing using water ponding",
  "Slab de-shuttering (after curing)",
  "Prop removal (after required duration)",
  "Wall masonry on first floor",
  "AAC block cutting",
  "AAC block adhesive mixing",
  "AAC block laying",
  "Window sill casting",
  "Door opening lintel checking",
  "Internal partition wall construction",
  "External wall plaster marking",
  "Plaster mortar mixing",
  "Plastering first coat (scratch coat)",
  "Plastering second coat (finish coat)",
  "Plaster curing",
  "External plaster scaffolding setup",
  "Waterproofing chemical mixing",
  "Bathroom waterproofing",
  "Terrace waterproofing",
  "Waterproof layer curing",
  "Cement screed preparation",
  "Terrace slope checking",
  "Plumbing pipe marking on wall",
  "Plumbing chasing cutting",
  "CPVC pipe cutting",
  "CPVC pipe joint solvent application",
  "Plumbing pipe fixing using clamps",
  "Pressure test for plumbing",
  "UPVC pipe joint fixing",
  "Bathroom trap installation",
  "Gully trap installation",
  "Kitchen water line installation",
  "Overhead tank connection",
  "Underground water line installation",
  "Rainwater downpipe installation",
  "Electrical conduit chasing",
  "Electrical conduit fixing",
  "Electrical box installation",
  "Fan box installation",
  "Junction box installation",
  "Wiring pulling",
  "MCB panel wiring",
  "Earthing pit digging",
  "Earthing electrode installation",
  "Earthing charcoal & salt filling",
  "Earthing chamber construction",
  "Electrical insulation testing",
  "AC copper piping layout",
  "AC drain pipe installation",
  "AC outdoor unit fixing",
  "AC refrigerant charging",
  "AC testing",
  "Ducting layout marking",
  "GI duct fabrication",
  "GI duct installation",
  "Flexible duct installation",
  "Diffuser fixing",
  "Insulation of ducts",
  "Fire hydrant pipe installation",
  "Fire sprinkler pipe installation",
  "Sprinkler head fixing",
  "Fire alarm cable laying",
  "Smoke detector installation",
  "Fire panel wiring",
  "Lift pit construction",
  "Lift machine room slab casting",
  "Lift rail installation",
  "Lift door frame fitting",
  "Lift cabin installation",
  "Lift testing & commissioning",
  "CCTV cable laying",
  "CCTV camera installation",
  "DVR/NVR setup",
  "Biometric access control installation",
  "Server rack installation",
  "Networking cable termination",
  "Switch installation",
  "Router setup",
  "Raised flooring installation (server room)",
  "Glass façade frame installation",
  "Aluminium channel leveling",
  "Glazing bead installation",
  "Glass panel fixing",
  "ACP sheet cutting",
  "ACP sheet fastening",
  "Sealant application on façade",
  "UPVC window frame installation",
  "UPVC sash fixing",
  "Glass installation in UPVC frame",
  "Silicone sealing",
  "Metal railing fabrication",
  "Railing welding",
  "Railing fixing using anchor bolts",
  "Gate fabrication",
  "Gate painting",
  "Gate installation",
  "Automatic gate motor fitting",
  "Door frame plumb checking",
  "Wooden door shutter cutting",
  "Door hinge installation",
  "Door lock installation",
  "Gypsum ceiling frame layout",
  "Ceiling channel installation",
  "Gypsum board cutting",
  "Gypsum board screw fixing",
  "Gypsum joint taping",
  "POP punning",
  "Grid ceiling tile installation",
  "Wooden flooring underlayer fixing",
  "Wooden flooring panel installation",
  "Tile layout marking",
  "Tile adhesive mixing",
  "Tile cutting",
  "Tile laying",
  "Tile joint grouting",
  "Skirting installation",
  "Marble cutting",
  "Marble polishing",
  "Granite countertop cutting",
  "Granite fitting",
  "Sink installation",
  "CP fitting installation (taps, mixers)",
  "WC installation",
  "Flush tank installation",
  "Shower panel installation",
  "Painting putty application",
  "Sanding walls",
  "Primer coating",
  "First coat painting",
  "Second coat painting",
  "Texture paint application",
  "Lighting fixture installation",
  "Switchboard fixing",
  "Socket installation",
  "Ceiling fan installation",
  "Exhaust fan installation",
  "Smart home hub installation",
  "Sensor installation (PIR, lighting, gas)",
  "Motorized curtain setup",
  "Solar panel mounting structure installation",
  "Solar panel fixing",
  "Solar inverter installation",
  "Battery bank wiring",
  "STP tank excavation",
  "STP tank installation",
  "Aeration system setup",
  "WTP installation",
  "Borewell drilling",
  "Bore casing pipe installation",
  "Bore submersible pump installation",
  "Landscaping soil filling",
  "Lawn preparation",
  "Plant plantation",
  "Drip irrigation pipe installation",
  "Paver block installation",
  "Paver compaction using plate compactor",
  "Paver joint sand filling",
  "Compound wall footing excavation",
  "Compound wall reinforcement tying",
  "Compound wall shuttering",
  "Compound wall concreting",
  "Compound wall plastering",
  "Main gate pillar construction",
  "Gate pillar cladding",
  "Security room construction",
  "Guard room electrical wiring",
  "Rainwater harvesting pit excavation",
  "RWH pit brick lining",
  "RWH filter media filling",
  "RWH pipe connection to tank",
  "Stormwater drain construction",
  "Kerb stone installation",
  "Road marking paint application",
  "Streetlight pole foundation",
  "Streetlight pole installation",
  "Streetlight wiring",
  "Streetlight LED fitting installation",
  "Underground cable trenching",
  "Cable marker plate fixing",
  "Cable laying on sand cushion",
  "Cable protection tile installation",
  "Cable backfilling",
  "Transformer foundation construction",
  "Transformer placement",
  "RMU (Ring Main Unit) installation",
  "HT cable termination",
  "LT cable termination",
  "Panel board installation",
  "Busbar installation",
  "Panel earthing",
  "Distribution board wiring",
  "MCC installation (Motor Control Center)",
  "VFD installation (Variable Frequency Drive)",
  "BMS (Building Management System) panel installation",
  "BMS sensor installation",
  "AHU installation in HVAC room",
  "AHU duct connection",
  "AHU drain connection",
  "Chiller pipeline installation",
  "Chilled water pump installation",
  "Copper insulation for chilled pipes",
  "VRF outdoor unit installation",
  "VRF indoor cassette installation",
  "VRF refrigerant piping",
  "VRF pressure testing",
  "VRF vacuuming",
  "VRF gas charging",
  "Cooling tower assembly",
  "Cooling tower basin waterproofing",
  "Cooling tower fan alignment",
  "Cooling tower vibration test",
  "Diesel generator foundation construction",
  "DG set placement",
  "DG exhaust pipeline fixing",
  "DG fuel tank installation",
  "DG earthing connection",
  "Acoustic enclosure installation",
  "UPS foundation setup",
  "UPS installation",
  "Battery bank rack installation",
  "Battery interconnection wiring",
  "Server room precision AC installation",
  "Server room floor cutout for cables",
  "Server rack grounding",
  "Cable tray installation",
  "Perforated cable tray fixing",
  "Ladder-type cable tray installation",
  "Cable tray earthing",
  "Trunking installation",
  "Fire-resistant cable laying",
  "Fiber optic cable blowing",
  "Fiber splicing",
  "Fiber termination in LIU",
  "Patch panel installation",
  "Access point (WiFi) mounting",
  "Router rack mounting",
  "POE switch installation",
  "Network cabinet ventilation fan installation",
  "EPABX system wiring",
  "Intercom handset installation",
  "PA system speaker installation",
  "PA system amplifier installation",
  "Fire-resistant door installation",
  "Panic bar installation on fire exit",
  "Fire-rated glass partition installation",
  "Fire curtain installation",
  "Emergency exit light fixing",
  "Directional signage installation",
  "Safety equipment storage cabinet fixing",
  "Fire bucket stand installation",
  "Fire extinguisher box installation",
  "FM200 gas suppression piping",
  "FM200 nozzles installation",
  "Gas suppression cylinder setup",
  "HVAC fire damper installation",
  "Smoke damper installation",
  "Air balancing for AHU",
  "VAV box installation",
  "VAV control wiring",
  "VRF indoor unit commissioning",
  "DFU (Drainage Fixture Unit) load testing",
  "Internal drainage line hydro testing",
  "External drainage line slope checking",
  "Sump pit excavation",
  "Sump tank construction",
  "Sump tank waterproof plaster",
  "Sump tank curing",
  "Water pump installation",
  "Pressure pump controller wiring",
  "Water level sensor installation",
  "Overhead tank pipeline connection",
  "Booster pump installation",
  "External pipeline backfilling",
  "Gutter installation",
  "Roof drain installation",
  "Roof parapet plastering",
  "Roof insulation board fixing",
  "APP membrane waterproofing",
  "Torch-on membrane installation",
  "Roof expansion joint sealing",
  "Solar mounting rail alignment",
  "Solar cable laying",
  "Solar MC4 connector crimping",
  "Solar combiner box installation",
  "Solar earthing strip fixing",
  "Lightning arrestor rod installation",
  "Lightning arrestor conductor fixing",
  "Lightning down conductor earthing",
  "Bonding testing",
  "Boundary lighting wiring",
  "Outdoor CCTV pole installation",
  "Outdoor camera weatherproof housing installation",
  "Gate access keypad installation",
  "RFID barrier gate installation",
  "Boom barrier balancing",
  "Boom barrier motor wiring",
  "Interlocking block road preparation",
  "Sand bedding filling",
  "Interlock block compaction",
  "Speed breaker installation",
  "Speed breaker painting",
  "Reflective road stud installation",
  "External wall cladding fixing",
  "Stone cladding adhesive mixing",
  "Stone cutting",
  "Stone cladding installation",
  "Exterior wall primer coating",
  "Exterior painting coat 1",
  "Exterior painting coat 2",
  "ACP façade rivet fixing",
  "Façade gasket installation",
  "Façade joint sealing",
  "Skylight frame installation",
  "Skylight glass installation",
  "Skylight flashing installation",
  "Atrium railing fixing",
  "Atrium glass installation",
  "Staircase formwork",
  "Staircase reinforcement",
  "Staircase concreting",
  "Staircase shuttering removal",
  "Staircase railing fabrication",
  "Staircase railing installation",
  "Handrail polishing",
  "Exterior staircase tile fixing",
  "Interior staircase granite fixing",
  "Lift lobby tiling",
  "Lift door frame alignment",
  "Lift landing door installation",
  "Lift indicator panel installation",
  "Lift emergency phone installation",
  "Lift full load testing",
  "Basement ventilation fan installation",
  "Jet fan installation",
  "CO sensor installation (parking)",
  "Parking marking layout",
  "Parking marking paint application",
  "Wheel stopper installation",
  "Parking signboard installation",
  "Traffic mirror installation",
  "Basement waterproof coating",
  "Basement wall plastering",
  "Basement sump cleaning",
  "Basement floor screed",
  "Shopfront glass fitting",
  "Aluminium sliding door installation",
  "Automatic sliding sensor door installation",
  "Revolving door installation",
  "Fire exit push bar testing",
  "Access control integration with doors",
  "IT server room earthing",
  "Raised floor panel installation",
  "Floor panel alignment",
  "Underfloor cable tray fixing",
  "Underfloor AC grille installation",
  "Data center humidity sensor installation",
  "Precision AC gas charging",
  "CRAC air balancing",
  "Data center smart locking installation",
  "Data center fire suppression testing",
  "Office workstation layout marking",
  "Modular workstation assembly",
  "Table top installation",
  "Pedestal installation",
  "Office chair unpacking",
  "Office chair assembling",
  "Conference room table installation",
  "Video conferencing camera setup",
  "Projector installation",
  "Projector screen installation",
  "Acoustic panel installation",
  "Soundproof door installation",
  "Meeting room glass writing board fixing",
  "Partition channel installation",
  "Gypsum partition board mounting",
  "Partition insulation filling",
  "Partition finishing",
  "Carpet tile layout planning",
  "Carpet tile fixing",
  "Vinyl roll flooring installation",
  "Epoxy flooring surface grinding",
  "Epoxy primer coat",
  "Epoxy base coat",
  "Epoxy top coat",
  "Anti-skid coating application",
  "Industrial floor curing",
  "Warehouse racking assembly",
  "Rack anchoring",
  "Rack safety barrier installation",
  "Loading dock leveling system installation",
  "Roller shutter installation",
  "Industrial shutter motor wiring",
  "Toilet partition measuring",
  "Toilet partition cutting",
  "Toilet partition installation",
  "Urinal divider installation",
  "Soap dispenser installation",
  "Hand dryer installation",
  "Sensor tap installation",
  "Flush valve installation",
  "Toilet exhaust duct connection",
  "GRC jali installation",
  "Pergola fabrication",
  "Pergola installation",
  "Rooftop machine foundation checking"
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'monthly',
    name: 'Monthly Plan',
    price: 99,
    originalPrice: 99,
    durationMonths: 1,
    saveLabel: '',
    recommended: false
  },
  {
    id: '3-month',
    name: '3-Month Plan',
    price: 249,
    originalPrice: 297,
    durationMonths: 3,
    saveLabel: 'Save 15%',
    recommended: false
  },
  {
    id: '6-month',
    name: '6-Month Plan',
    price: 449,
    originalPrice: 594,
    durationMonths: 6,
    saveLabel: 'Save 25%',
    recommended: true
  },
  {
    id: 'yearly',
    name: 'Yearly Plan',
    price: 699,
    originalPrice: 1188,
    durationMonths: 12,
    saveLabel: 'Save 40%',
    recommended: false
  }
];

export const PAYMENT_METHODS = [
  { id: 'upi', name: 'UPI (GPay, PhonePe, Paytm)', icon: '📱' },
  { id: 'card', name: 'Debit / Credit Card', icon: '💳' },
  { id: 'netbanking', name: 'Net Banking', icon: '🏦' },
  { id: 'wallet', name: 'Wallets', icon: '👛' },
];
